package-lock.json, package.json, src/App.test.tsx, src/App.tsx, src/layouts/Unauthed.tsx, src/pages/Home.tsx, src/pages/SignUp.tsx, src/pages/Splash.tsx, src/pages/StudentDashboard.tsx, yarn.lock
=> Chin layouts

.eslintrc.js, .storybook/main.ts, .storybook/preview.ts, package.json, src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/index.tsx, tsconfig.json, vite.config.ts, yarn.lock
- started Input convenience component
- started unit testing and stories
- added storybook
=> added initial convenience code

src/App.tsx, src/components/RadioCard/RadioCard.tsx, src/components/RadioCard/index.tsx, src/pages/SignUp/AccountCredentials.tsx, src/pages/SignUp/RoleSelect.tsx, src/theme/overrides.scss, src/theme/variables.css
Role Select works though setData() has to be commented out. AccountCredential page works but not swipes to the next slide. I guess for the same reason: setData()  :)))
=> Chin swiperjs

src/components/RadioCard/RadioCard.tsx, src/pages/SignUp/AccountCredentials.tsx, src/pages/SignUp/Complete.tsx, src/pages/SignUp/LanguageInclusivitySelect.tsx, src/pages/SignUp/LanguageModeSelect.tsx, src/pages/SignUp/RoleSelect.tsx, src/pages/SignUp/SignUp.tsx, src/pages/SignUp/TeacherAccountCredentials.tsx, src/pages/SignUp/index.tsx, src/theme/overrides.scss, src/theme/variables.css
Buton was disabled on Complete.tsx. Slides were updated using zod library. A badge was added to the LanguageInclusivity.
=> SignUp slides

.gitignore, packages/app/src/App.tsx
removed redundant component load in App.tsx
=> added .yarn/install-state.gz to .gitignore

packages/app/package.json, packages/app/src/App.tsx, packages/app/src/components/I18nWrapper/lang/en.json, packages/app/src/components/Settings/SettingsExplore/SettingsExploreCard.css, packages/app/src/components/Settings/SettingsExplore/SettingsExploreCard.tsx, packages/app/src/components/Settings/SettingsHeader/SettingsHeader.css, packages/app/src/components/Settings/SettingsHeader/SettingsHeader.tsx, packages/app/src/components/Settings/SideMenu/SideMenu.css, packages/app/src/components/Settings/SideMenu/SideMenu.tsx, packages/app/src/layouts/Authed.tsx, packages/app/src/layouts/Container.css, packages/app/src/layouts/Settings.tsx, packages/app/src/pages/Login.tsx, packages/app/src/pages/Settings/Overview.tsx, packages/app/src/pages/Settings/Preferences.css, packages/app/src/pages/Settings/Preferences.tsx, packages/app/src/pages/Settings/Progress.css, packages/app/src/pages/Settings/Progress.tsx, packages/app/src/pages/SignUp/ChildProfile.tsx, packages/app/src/pages/SignUp/Complete.tsx, packages/app/src/pages/SignUp/Pricing.tsx, yarn.lock
- Added React-intl to all completed settings pages (and added id's and translations to en.json)
- Edited Side Menu to have shadow on the right and to line up flush against the edges
- Edited settings.overview and setting.progress (and corresponding css pages) to better match Figma
=> Fernanda replace hardcoded text

packages/app/src/components/Settings/SideMenu/SideMenu.css, packages/app/src/components/Settings/SideMenu/SideMenu.tsx, packages/app/src/components/Settings/SideMenu/SideMenuOption.tsx, packages/app/src/pages/Settings/Profile.css
- Edited `SideMenuOption.tsx` to add the prop for when a menu option is active
- Added classes for this ^ in `SideMenu.css`
=> Fernanda highlight active page

packages/app/src/pages/StudentDashboard.css, packages/app/src/pages/StudentDashboard.tsx
- overflowX: "scroll" was added to the cards
- size of the top cards was changed to aligned with the other cards
- margins were added to the main block
=> Scrollbars were added to the StudentDashboard.tsx

packages/app/src/components/I18nWrapper/lang/en.json, packages/app/src/components/I18nWrapper/lang/es.json, packages/app/src/components/Popover/Popover.tsx, packages/app/src/pages/Settings/Preferences.tsx, packages/app/src/pages/SignUp/LanguageModeSelect.tsx, packages/app/src/pages/SignUp/Pricing.tsx
- Resolved the following recent Github issues assigned to me:
- #136 
- #140 
- #149 
- #156
=> Fer assigned GitHub issues

packages/app/src/App.tsx, packages/app/src/components/ScrollToTop/ScrollToTop.tsx, packages/app/src/components/ScrollToTop/index.tsx
- Added `ScrollToTop` folder
- Within `ScrollToTop` are the following files:
- `ScrollToTop.tsx` which has the component code
- `index.tsx` which exports all from the component
- Wrapped `App.tsx` routes in `<ScrollToTop/>` component (also edited indentation of a few routes that were REALLY off on my screen)
=> ScrollToTop Component

packages/app/src/components/PackSelect/PackSelect.tsx, packages/app/src/layouts/Authed.tsx, packages/app/src/pages/Community/Community.scss, packages/app/src/pages/Community/Community.tsx, packages/app/src/pages/CountWithMe/CountWithMeSelect.tsx, packages/app/src/pages/Intruder/IntruderSelect.tsx, packages/app/src/pages/StoryFactory/StoryFactorySelect.tsx, packages/app/src/pages/StudentDashboard.tsx, packages/app/src/pages/WouldDo/WouldDoSelect.tsx
Updated pack select file for `WouldDoSelect.tsx`, `StoryFactorySelect.tsx`, and `IntruderSelect.tsx`
=> Fer pack select updates

packages/app/src/pages/CountWithMe/CountWithMeGame.tsx
- `CountWithMeGame.tsx`
- changes value of setCurrentIndex back to 0
=> changed variable setCurrentIndex back to 0

packages/app/src/components/PlayHeader/PlayHeader.scss, packages/app/src/components/PlayHeader/PlayHeader.tsx, packages/app/src/components/ProfileComingSoon/ComingSoonCard.scss, packages/app/src/pages/ProfileComingSoon/ProfileComingSoon.scss, packages/app/src/pages/ProfileComingSoon/ProfileComingSoon.tsx, packages/app/src/pages/StoryFactory/StoryFactory.scss, packages/app/src/pages/StoryFactory/StoryFactoryCongrats.tsx, packages/app/src/pages/StoryFactory/StoryFactoryIntro.tsx, packages/app/src/pages/StoryFactory/StoryFactoryPg4.tsx, packages/app/src/theme/animate.scss
- `StoriesLandingPage.tsx`/ `StoriesLandingPage.scss`
- Edited the alignment and padding
- Edited placement of Bili depending on screen sizes
- `PlayHeader.tsx`/`PlayHeader.scss`
- Fixed overlay
- `StoryFactoryCongrats.tsx`/`StoryFactory.scss`
-  Added 'horizontal bounce' animation to arrow
-  Fixed stars overlay so that no stars cover any text
- `Animate.scss`
- Added 'horizontal bounce' animation to use for congrats page arrow
=> Fer random fixes

packages/app/src/pages/Intruder/IntruderGame.tsx
- Changed the English text for the Intruder audio button to the correct one
=> Intruder audio button text was fixed

packages/app/src/App.tsx, packages/app/src/pages/CountWithMe/CountGameLoader.tsx, packages/app/src/pages/CountWithMe/CountWithMeGame.tsx
- GameLoader was created as a separate component
- The code was cleaned
- Created interface for CountWIthMeGame data types
=> CountWithMe game was updated

packages/app/src/pages/CountWithMe/CountWithMeGame.tsx
`CountWithMeGame.tsx`
- audio overlaying issue was fixed
- `const [isButtonDisabled, setIsButtonDisabled] = useState(false)` was added and used inside of `handleBirdClickOrder()`
- once a user clicks on the last animal button, all animal buttons will be disabled for 1700 seconds
=> Sasha count fix audio

packages/app/src/components/PackHeader/PackHeader.scss, packages/app/src/components/PackHeader/PackHeader.tsx, packages/app/src/components/PackHeader/index.tsx, packages/app/src/components/PackSelect/PackSelect.tsx, packages/app/src/pages/Stories/StoriesLandingPage.scss, packages/app/src/pages/Stories/StoriesLandingPage.tsx
- `StoriesLandingPage.tsx`: Includes new implementations for dynamic data fetching and layout adjustments.
- `StoriesLandingPage.scss`: Style adjustments to align with updated component structure.
- `PackSelect.tsx`: Modified to integrate with new changes from `Stories`
- `PackHeader`: this new component is designed for reusable header presentations and was used for the Stories Header
- Code refactoring was performed to remove redundant code
=> Sasha stories fix

packages/app/src/pages/Intruder/IntruderCongrats.tsx
**Updated: Congratulations Page for Intruder Game
- Full Coverage: The Congratulations page now appears every time a user finishes all available games.
- Condition Update: Implemented `count === 0` to trigger the Congratulations page under the specified scenario.
=> Fixed Intruder Congratulation when all games are done

packages/app/src/pages/CountWithMe/CountWithMeFacts.tsx, packages/app/src/pages/CountWithMe/CountWithMeGame.tsx
**Resolved: Audio Truncation Issue in Bilingual Mode for CountWithMeGame.tsx**
- Nested the check `if (clickedIndexes.length + 1 === getData.animalImages.length)` within `if (clickedIndexes.length + 1 
<= getData.animalImages.length)`
- Removed the `setTimeout()` function and replaced it with `setCallback()`, 
ensuring audio files are fully played without interruption
=> setCallBack() was added to CountWithMeGame.tsx

packages/app/package.json, packages/app/src/components/DnD/DnD.css, packages/app/src/components/DnD/DnD.tsx, packages/app/src/components/DnD/DropTarget.tsx, packages/app/src/components/DnD/Piece.tsx, packages/app/src/components/DnD/index.tsx, packages/app/src/components/Router.tsx, packages/app/src/hooks/DnD.tsx, packages/app/src/pages/DnD.tsx, packages/app/src/theme/color-classes.scss, packages/story_factory_audio/run.js, packages/story_factory_audio/run_en.js, yarn.lock
updated scripts to only generate full sentences
=> Chin refactor sf audio

packages/app/src/pages/StudentProfile/StudentProfile.tsx
- Fix for the issue `Update Student Profile Classroom label #290`
=> Classroom name was updated

packages/app/src/pages/SignUp/ClassCode.tsx, packages/app/src/pages/SignUp/LanguageModeSelect.tsx, packages/app/src/pages/SignUp/TeacherAbout.tsx
- Updated code to fit the Figma design for Parent onboarding:
* Added English immersion RadioButton
* Changed icon's design
- Updated values for the ExtendedRadioOption
- Deleted LangugeSelectPage from the Teacher onboarding
- Cleaned up some code
=> Sasha parent dashboard

packages/app/src/pages/SignUp/ClassCode.scss, packages/app/src/pages/SignUp/TeacherAbout.scss, packages/app/src/pages/SignUp/TeacherAbout.tsx, packages/app/src/pages/SignUp/TeacherAccountCredentials.tsx
=> Sasha teacher onboard

packages/app/src/pages/TeacherDashboard/AddClassroom.scss, packages/app/src/pages/TeacherDashboard/AddClassroom.tsx
- Implemented AddClassroom.tsx page
- Added styles to the AddClassroom.scss
=> Sasha teacher dashboard

packages/app/src/pages/SignUp/TeacherAbout.tsx, packages/app/src/pages/TeacherDashboard/AddClassroom/AddClassroomLanguage.tsx
- Updated Language preferences cards text: change it from the `child` to the `classroom`
- Updated school names to the real names on Teacher creating account process
=> Sasha updates

packages/app/src/pages/Stories/Stories.css, packages/app/src/pages/Stories/Stories.tsx
- Updated `Stories.tsx` and `Stories.css`
- Added these styles to fix the pills issue :
`.stories-pills-block {
display: flex;
max-width: 700px;
height: 7.536px;
align-items: flex-start;
}`
`.stories-card-pills-block {
display: flex;
flex-direction: column;
align-items: center;
}`
=> Updated pills for the stories

package.json, packages/app/src/components/Settings/SettingsExplore/SettingsExploreCard.scss, packages/app/src/components/Settings/SettingsExplore/SettingsExploreCard.tsx, packages/app/src/pages/Settings/Overview/Overview.tsx, packages/app/src/pages/TeacherDashboard/MyClassrooms.tsx, yarn.lock
- Installed capacitor browser (needs testing in XCode)
- Added `link` prop to SettingsExploreCard component (optional for now)
- `handleCardClick` opens link with capacitor browser
- Added appropriate links to explore cards in `Settings/Overview` and `TeacherDashboard/MyClassrooms`
=> Explore card links

packages/app/src/components/DialogueScreen/DialogueScreen.tsx, packages/app/src/pages/WouldDo/WouldDoIntro.tsx
removed margin classes and changed height to 100%
=> Dialogue screen margin update

packages/app/src/components/AudioButton.tsx, packages/app/src/pages/Affirmations/AffirmationsGame.tsx, packages/app/src/pages/Community/CommunityCongrats.tsx, packages/app/src/pages/Community/FeelingsFeedback.tsx, packages/app/src/pages/Community/ThoughtsFeedback.tsx
- Thoughts feedback and Feelings feedback were connected to the AffirmationsGame
- Her is the logic for switching between Thoughts and Feelings:  `if (uniqueClickCount > 0 && uniqueClickCount % 5 === 0) {
const destination =
(uniqueClickCount / 5) % 2 === 0
? "/community/thoughts"
: "/community/feelings";
history.push(destination, {
cardIndex: nextCardIndex,
pack_id: pack_id,
uniqueClicks: uniqueClickCount,
}); `
- These states are passed between AffirmationsGames, Feedbacks, and Congrats screen, so users can get back to the same Affirmation Card once they leave feedback: 
` const { state } = useLocation<{
cardIndex?: number;
uniqueClicks?: number;
}>();
const { pack_id } = useParams<{ pack_id: string }>(); `
- AudioButton got a new prop: ` onClick?: () => void;` so we could handle Audio …
=> Affirmations feedback

packages/app/src/components/LanguageToggle/LanguageToggle.scss
- Changed `bottom` and `left` of language-toggle class from `1rem` to `2rem`.
=> Updated language-toggle bottom and left positions

packages/app/src/components/LanguageToggle/LanguageToggle.scss
Changed language-toggle `bottom` from `2rem` to `3rem`.
=> Updated language-toggle bottom to 3rem

packages/scripts/package.json, packages/scripts/src/rtdb_dump.ts
Added new script to dump from realtime database
=> rtdb dump script

packages/app/src/hooks/dictionaries/en.json
- Updated `Family and Community` title in locize
=> Updated Family and Community title in locize

packages/app/src/pages/Stories/StoriesCongrats.tsx
Updated Bili image in Stories Congrats
=> Updated Bili image for stories congrats

packages/app/src/pages/Intruder/IntruderGame.tsx, packages/app/src/pages/StoryFactory/EarlyReader.tsx
- Removed text from the `Read` button from the `Intruder` game and `StoryFactory` game.
=> Removed text from the Read button

packages/app/src/pages/Intruder/IntruderCongrats.tsx, packages/app/src/pages/StoryFactory/EarlyReader.tsx, packages/app/src/pages/StoryFactory/StoryFactoryCongrats.tsx
Updated StoryFactoryCongrats page:
- Cleaned up code
- Commented out ActivityContext until it's implemented
- Temporary updated stars to be always equal to 1 for now
- Temporary commented out percentage text 
- Updated Dialog screen to follow the new logic
=> Updated StoryFactoryCongrats

packages/app/src/pages/Intruder/IntruderGame.tsx
- Added ` const { language, setIsVisible } = useLanguageToggle();`  to the IntruderGame
- Added `useEffect(() => {
setIsVisible(false);
return () => {
setIsVisible(true);
};
});` to the IntruderGame to remove language mode button
=> Removed language mode button

packages/app/src/pages/Feedback/Feeling.scss, packages/app/src/pages/Feedback/Feeling.tsx
Updated FeelingCard:
- Updated styles to `ion-card`
- Created `FeelingCard` component inside of `Feeling.tsx`
- Added new properties to `options` object
- Moved option creation logic from map callback to `generateOption`
- Added text-classes to the `ion-text`
=> Sasha feeling card update

packages/app/src/components/DialogueScreen/DialogueScreen.tsx, packages/app/src/pages/Stories/StoryPage.tsx, packages/app/src/theme/margin-classes.scss
[**Original Issue**](https://github.com/bilingualgeneration/bili-app/issues/725)
- Created right column (2:1 ratio)
- Switched character image from background to right column
=> Dialog screen overlap
